# Generated by Django

from django.db import migrations
import datetime


def add_sample_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    sample_events = [
        {
            'name': 'Annual Tech Symposium',
            'description': 'A day-long technical symposium featuring workshops, coding competitions, and tech talks.',
            'date': '2025-01-15',
            'venue': 'Main Auditorium'
        },
        {
            'name': 'Cultural Fest 2025',
            'description': 'Annual cultural festival with music, dance, and theatrical performances.',
            'date': '2025-02-20',
            'venue': 'College Ground'
        },
        {
            'name': 'Winter Sports Meet',
            'description': 'Inter-college sports competition featuring various indoor and outdoor games.',
            'date': '2025-10-05',
            'venue': 'Sports Complex'
        },
        {
            'name': 'Career Fair 2025',
            'description': 'Connect with top companies and explore career opportunities.',
            'date': '2025-03-10',
            'venue': 'Conference Center'
        },
        {
            'name': 'AI & Machine Learning Workshop',
            'description': 'Hands-on workshop on artificial intelligence and machine learning fundamentals.',
            'date': '2025-02-28',
            'venue': 'Computer Lab Complex'
        }
    ]
    
    for event_data in sample_events:
        Event.objects.create(**event_data)


def remove_sample_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(name__in=[
        'Annual Tech Symposium',
        'Cultural Fest 2025',
        'Winter Sports Meet',
        'Career Fair 2025',
        'AI & Machine Learning Workshop'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_events, remove_sample_events),
    ]
