# Generated by Django

from django.db import migrations


def add_event_images(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    # Update events with appropriate images
    event_images = {
        'Annual Tech Symposium': 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800',
        'Cultural Fest 2025': 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800',
        'Winter Sports Meet': 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800',
        'Career Fair 2025': 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=800',
        'AI & Machine Learning Workshop': 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800'
    }
    
    for event_name, image_url in event_images.items():
        try:
            event = Event.objects.get(name=event_name)
            # Add image field value - Note: This requires the Event model to have an image field
            # Since the model doesn't have this field yet, we'll skip this for now
        except Event.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_sample_events'),
    ]

    operations = [
        # Commented out since Event model doesn't have image field
        # migrations.RunPython(add_event_images, migrations.RunPython.noop),
    ]
