# Generated by Django 5.2.5 on 2025-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_event_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800', max_length=500),
        ),
    ]
