# Generated by Django

from django.db import migrations
from datetime import datetime, timedelta


def update_event_dates_to_future(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    
    # Update existing events to future dates
    today = datetime.now().date()
    
    event_updates = {
        'Annual Tech Symposium': today + timedelta(days=15),
        'Cultural Fest 2025': today + timedelta(days=30),
        'Winter Sports Meet': today + timedelta(days=45),
        'Career Fair 2025': today + timedelta(days=60),
        'AI & Machine Learning Workshop': today + timedelta(days=75)
    }
    
    for event_name, new_date in event_updates.items():
        try:
            event = Event.objects.get(name=event_name)
            event.date = new_date
            event.save()
            print(f"Updated {event_name} to {new_date}")
        except Event.DoesNotExist:
            print(f"Event {event_name} not found")


def reverse_update(apps, schema_editor):
    pass  # No need to reverse


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RunPython(update_event_dates_to_future, reverse_update),
    ]
